export const GET_FULLDATA_REQUEST = 'GET_FULLDATA_REQUEST';
export const GET_FULLDATA_SUCCESS = 'GET_FULLDATA_SUCCESS';
export const GET_FULLDATA_FAILED = 'GET_FULLDATA_FAILED';

export const SET_INGREDIENT_INFO = 'SET_INGREDIENT_INFO'
export const CLEAR_INGREDIENT_INFO = 'CLEAR_INGREDIENT_INFO'

export const ADD_INGREDIENT_TO_CONSTRUCTOR = 'ADD_INGREDIENT_TO_CONSTRUCTOR'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const ADD_BUN_TO_CONSTRUCTOR = 'ADD_BUN_TO_CONSTRUCTOR'

export const REFRESH_TOTAL = 'REFRESH_TOTAL'