export const GET_FULLDATA_REQUEST = 'GET_FULLDATA_REQUEST';
export const GET_FULLDATA_SUCCESS = 'GET_FULLDATA_SUCCESS';
export const GET_FULLDATA_FAILED = 'GET_FULLDATA_FAILED';

export const SET_INGREDIENT_INFO = 'SET_INGREDIENT_INFO'
export const CLEAR_INGREDIENT_INFO = 'CLEAR_INGREDIENT_INFO'