export const REGISTER_REQUEST : 'REGISTER_REQUEST' = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS : 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS';
export const REGISTER_FAILED : 'REGISTER_FAILED' = 'REGISTER_FAILED';

export const LOGIN_REQUEST : 'LOGIN_REQUEST' = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS : 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS'
export const LOGIN_FAILED : 'LOGIN_FAILED' = 'LOGIN_FAILED'

export const USER_RELOGIN_REQUEST : 'USER_RELOGIN_REQUEST' = 'USER_RELOGIN_REQUEST'
export const USER_RELOGIN_SUCCESS : 'USER_RELOGIN_SUCCESS' = 'USER_RELOGIN_SUCCESS'
export const USER_RELOGIN_FAILED : 'USER_RELOGIN_FAILED' = 'USER_RELOGIN_FAILED'

export  const PASSWORD_RESET_REQUEST : 'PASSWORD_RESET_REQUEST' = 'PASSWORD_RESET_REQUEST'
export  const PASSWORD_RESET_SUCCESS : 'PASSWORD_RESET_SUCCESS' = 'PASSWORD_RESET_SUCCESS'
export  const PASSWORD_RESET_FAILED : 'PASSWORD_RESET_FAILED' = 'PASSWORD_RESET_FAILED'